config: generify about and how-to placeholders
novoid/lazyblorg pull request #81
Opened 2022-09-16 21:23 UTC by xeruf

2022-09-16 21:36 UTC, xeruf commented
Also added copying css to get a functional page by default.

2022-09-18 14:43 UTC, novoid approved these changes

2022-09-18 14:48 UTC, novoid requested changes
I can't accept this change.

Although it might seem that the date-stamp in the ID is not important for lazyblorg, it is very important for a general Org-mode setup. IDs need to be unique in all my agenda files. Currently I do have 67524 headings and most of them do have (in my case auto-generated) IDs.

It is true that somebody might think that it should not be "2022-09-18-about" (or similar) but "about" since the about-page is not related to any particular date (persistent page).

At the same time, I could not have any other heading with that ID in order to fulfill the uniqueness constraint. For that, all my IDs do contain a date-stamp and I do think it is important to notice that users of lazyblorg might follow that pattern. Therefore, lazyblorg does not use that datestamp for any reason but it is able to ignore it which is the more important fact here.

2022-09-18 14:49 UTC, novoid commented
I'd accept one of those patches. So if you get rid of the other, I can merge. I don't know if Github allows me to merge one of your two patches while ignoring the other.

2022-09-18 16:54 UTC, xeruf commented
Ah, I was not aware that the datestamp is cut away. Well then we could change it to a fictional date to make that clear, like `0000-00-00`, hm?

You can add my repo as remote and cherry-pick it :)

2022-09-18 17:02 UTC, novoid commented
> Ah, I was not aware that the datestamp is cut away. Well then we could change it to a fictional date to make that clear, like `0000-00-00`, hm?

Yes, that is a possibility although I don't care to do so because the datestamp is cut in all IDs, not only persistent ones. So it really doesn't matter if and which date-stamp you're using there. That's not special for that particular heading, that's a generic behavior of lazyblorg to be able to work with unique IDs and sill get generic URLs.

> You can add my repo as remote and cherry-pick it :)

Ah, I may play around with that idea some day.

2022-09-18 17:02 UTC, closed without merging

2022-09-18 20:33 UTC, xeruf commented
Alternatively we could make the id more specific like `about-this-blog` so there is no duplication.

Btw, do you have any reference how you generate org-ids? I always work with custom ids and org tends to be a bit reluctant about that ;)

2022-09-18 21:40 UTC, novoid commented
> Alternatively we could make the id more specific like `about-this-blog` so there is no duplication.

That would still potentially interfere with use-cases where one person does maintain two different lazyblorg setups in parallel. In general, you're right: the convention to name persistent default pages could be a different one.

> Btw, do you have any reference how you generate org-ids? I always work with custom ids and org tends to be a bit reluctant about that ;)

You should read https://github.com/novoid/dot-emacs/blob/master/config.org and look for all occurrences of `my-id-get-or-generate` which I'm using to generate IDs most of the time. For lazyblorg articles, I tend to write them manually in order to make the URL path as short as possible and as expressive as possible.